from enum import StrEnum


class Aduana(StrEnum):
    A_01 = '01'
    """ACAPULCO, ACAPULCO DE JUAREZ, GUERRERO."""
    A_02 = '02'
    """AGUA PRIETA, AGUA PRIETA, SONORA."""
    A_05 = '05'
    """SUBTENIENTE LOPEZ, SUBTENIENTE LOPEZ, QUINTANA ROO."""
    A_06 = '06'
    """CIUDAD DEL CARMEN, CIUDAD DEL CARMEN, CAMPECHE."""
    A_07 = '07'
    """CIUDAD JUAREZ, CIUDAD JUAREZ, CHIHUAHUA."""
    A_08 = '08'
    """COATZACOALCOS, COATZACOALCOS, VERACRUZ."""
    A_11 = '11'
    """ENSENADA, ENSENADA, BAJA CALIFORNIA."""
    A_12 = '12'
    """GUAYMAS, GUAYMAS, SONORA."""
    A_14 = '14'
    """LA PAZ, LA PAZ, BAJA CALIFORNIA SUR."""
    A_16 = '16'
    """MANZANILLO, MANZANILLO, COLIMA."""
    A_17 = '17'
    """MATAMOROS, MATAMOROS, TAMAULIPAS."""
    A_18 = '18'
    """MAZATLAN, MAZATLAN, SINALOA."""
    A_19 = '19'
    """MEXICALI, MEXICALI, BAJA CALIFORNIA."""
    A_20 = '20'
    """MEXICO, DISTRITO FEDERAL."""
    A_22 = '22'
    """NACO, NACO, SONORA."""
    A_23 = '23'
    """NOGALES, NOGALES, SONORA."""
    A_24 = '24'
    """NUEVO LAREDO, NUEVO LAREDO, TAMAULIPAS."""
    A_25 = '25'
    """OJINAGA, OJINAGA, CHIHUAHUA."""
    A_26 = '26'
    """PUERTO PALOMAS, PUERTO PALOMAS, CHIHUAHUA."""
    A_27 = '27'
    """PIEDRAS NEGRAS, PIEDRAS NEGRAS, COAHUILA."""
    A_28 = '28'
    """PROGRESO, PROGRESO, YUCATAN."""
    A_30 = '30'
    """CIUDAD REYNOSA, CIUDAD REYNOSA, TAMAULIPAS."""
    A_31 = '31'
    """SALINA CRUZ, SALINA CRUZ, OAXACA."""
    A_33 = '33'
    """SAN LUIS RIO COLORADO, SAN LUIS RIO COLORADO, SONORA."""
    A_34 = '34'
    """CIUDAD MIGUEL ALEMAN, CIUDAD MIGUEL ALEMAN, TAMAULIPAS."""
    A_37 = '37'
    """CIUDAD HIDALGO, CIUDAD HIDALGO, CHIAPAS."""
    A_38 = '38'
    """TAMPICO, TAMPICO, TAMAULIPAS."""
    A_39 = '39'
    """TECATE, TECATE, BAJA CALIFORNIA."""
    A_40 = '40'
    """TIJUANA, TIJUANA, BAJA CALIFORNIA."""
    A_42 = '42'
    """TUXPAN, TUXPAN DE RODRIGUEZ CANO, VERACRUZ."""
    A_43 = '43'
    """VERACRUZ, VERACRUZ, VERACRUZ."""
    A_44 = '44'
    """CIUDAD ACUÑA, CIUDAD ACUÑA, COAHUILA."""
    A_46 = '46'
    """TORREON, TORREON, COAHUILA."""
    A_47 = '47'
    """AEROPUERTO INTERNACIONAL DE LA CIUDAD DE MEXICO,"""
    A_48 = '48'
    """GUADALAJARA, TLACOMULCO DE ZUÑIGA, JALISCO."""
    A_50 = '50'
    """SONOYTA, SONOYTA, SONORA."""
    A_51 = '51'
    """LAZARO CARDENAS, LAZARO CARDENAS, MICHOACAN."""
    A_52 = '52'
    """MONTERREY, GENERAL MARIANO ESCOBEDO, NUEVO LEON."""
    A_53 = '53'
    """CANCUN, CANCUN, QUINTANA ROO."""
    A_64 = '64'
    """QUERÉTARO, EL MARQUÉS Y COLON, QUERÉTARO."""
    A_65 = '65'
    """TOLUCA, TOLUCA, ESTADO DE MEXICO."""
    A_67 = '67'
    """CHIHUAHUA, CHIHUAHUA, CHIHUAHUA."""
    A_73 = '73'
    """AGUASCALIENTES, AGUASCALIENTES, AGUASCALIENTES."""
    A_75 = '75'
    """PUEBLA, HEROICA PUEBLA DE ZARAGOZA, PUEBLA."""
    A_80 = '80'
    """COLOMBIA, COLOMBIA, NUEVO LEON."""
    A_81 = '81'
    """ALTAMIRA, ALTAMIRA, TAMAULIPAS."""
    A_82 = '82'
    """CIUDAD CAMARGO, CIUDAD CAMARGO, TAMAULIPAS."""
    A_83 = '83'
    """DOS BOCAS, PARAISO, TABASCO."""
    A_84 = '84'
    """GUANAJUATO, SILAO, GUANAJUATO."""
    A_85 = '85'
    """AEROPUERTO INTERNACIONAL FELIPE ÁNGELES, SANTA LUCÍA, ZUMPANGO, ESTADO DE MÉXICO."""
